services:
    # UTILS
    MNC\Bundle\RestBundle\Doctrine\Utils\QueryNameGenerator:
        public: false

    # EVENT LISTENERS
    MNC\Bundle\RestBundle\EventListener\RequestBodyListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 150 }

    MNC\Bundle\RestBundle\EventListener\FormatListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: -40 }

    MNC\Bundle\RestBundle\EventSubscriber\DoctrineFilterSubscriber:
        arguments:
            - '@MNC\Bundle\RestBundle\Doctrine\Utils\QueryNameGenerator'
        tags:
            - { name: kernel.event_subscriber }

    # FILTERS
    MNC\Bundle\RestBundle\DoctrineFilter\OrderFilter:
        tags:
            - mnc_rest.doctrine_filter
    MNC\Bundle\RestBundle\DoctrineFilter\WhereFilter:
        tags:
            - mnc_rest.doctrine_filter

    # VOTERS
    MNC\Bundle\RestBundle\Security\ProtectedResourceVoter:
        tags:
            - { name: security.voter }

    # SERVICES
    MNC\Bundle\RestBundle\Fractalizer\Fractalizer:
        arguments:
            - '@Symfony\Component\HttpFoundation\RequestStack'
            - '@router'
            - '@MNC\Bundle\RestBundle\Fractalizer\ContainerAwareManager'
            - '@event_dispatcher'
            - '@MNC\Bundle\RestBundle\Manager\QueryParser'
        public: true

    MNC\Bundle\RestBundle\Fractalizer\ContainerAwareManager:
        public: true
        calls:
            - [setContainer, ['@service_container']]

    MNC\Bundle\RestBundle\EntityFactory\EntityFactory:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@MNC\Bundle\RestBundle\EntityFactory\FactoryDefinitionLoader'
        calls:
            - [loadDefinitions, []]

    MNC\Bundle\RestBundle\EntityFactory\FactoryDefinitionLoader:
        public: false

    MNC\Bundle\RestBundle\Manager\ResourceManagerFactory:
        public: true

    MNC\Bundle\RestBundle\Manager\ResourceManagerFactoryInterface:
        alias: MNC\Bundle\RestBundle\Manager\ResourceManagerFactory
        public: true

    MNC\Bundle\RestBundle\Manager\AbstractResourceManager:
        abstract: true
        public: false
        arguments: ['@service_container']

    MNC\Bundle\RestBundle\Serializer\FormErrorNormalizer:
        arguments: ['@translator.default']
        tags:
            - { name: serializer.normalizer }

    mnc_rest.form_error_normalizer:
        alias: MNC\Bundle\RestBundle\Serializer\FormErrorNormalizer
        public: true

    MNC\Bundle\RestBundle\Manager\QueryParser:
        public: true
        arguments: ['@request_stack']

    MNC\Bundle\RestBundle\Command\CreateResourceSetCommand:
        tags:
            - { name: console.command }

    MNC\Bundle\RestBundle\Maker\MakeTransformer:
        arguments: ['@maker.doctrine_entity_helper']
        tags:
            - { name: maker.command }

    MNC\Bundle\RestBundle\Maker\MakeManager:
        arguments: ['@maker.doctrine_entity_helper']
        tags:
            - { name: maker.command }

    MNC\Bundle\RestBundle\Maker\MakeEntityFactory:
        arguments: ['@maker.doctrine_entity_helper']
        tags:
            - { name: maker.command }

    MNC\Bundle\RestBundle\Maker\MakeAdvancedFixture:
        arguments: ['@maker.doctrine_entity_helper']
        tags:
            - { name: maker.command }

    MNC\Bundle\RestBundle\Maker\MakeRestController:
        arguments: ['@maker.doctrine_entity_helper']
        tags:
            - { name: maker.command }
